✨ add button-chaser-vector
LouisaStrunk02/Button-Chaser pull request #4
Opened 2022-09-13 08:56 UTC by LouisaStrunk02

Changes:

1. add button-chaser-vector.html
2. add button-chaser-vector.css
3. add button-chaser-vector.js

2022-09-13 13:01 UTC, stefanluth requested changes

2022-09-13 13:01 UTC, stefanluth commented on button-chaser-vector/button-chaser-vector.js
> +    var buttonIsBottomRight = (button.offsetLeft + buttonWidth) >= (projectContainer.offsetTop + projectContainer.offsetWidth - border) && (button.offsetTop + buttonHeight) >= (projectContainer.offse
You can extract some of the calculations into variables, e.g.

```
    var a = button.offsetLeft + buttonWidth;
    var b = projectContainer.offsetLeft + border;
```

With proper names of course :D

2022-09-14 06:32 UTC, DevBastiS approved these changes

2022-09-14 06:32 UTC, DevBastiS commented on button-chaser-vector/button-chaser-vector.js
> +    const buttonWidth = button.offsetWidth;
Could be declared above the function.

2022-09-16 06:41 UTC, DevBastiS approved these changes

2022-09-16 08:19 UTC, stefanluth approved these changes

2022-09-16 11:27 UTC, merged